pipeline{
  agent any
  stages{
    stage('Clone repository'){
        steps{
          checkout([
            $class: 'GitSCM',
            branches: [[name: '*/main']],
            userRemoteConfigs: [[url: "https://github.com/NavyaPeram/PES1UG21CS924_Jenkins.git/"]]
          ])
        }
    }

    stage('Build'){
        steps{
            build 'PES1UG21CS924-1'
            sh 'g++ /var/jenkins_home/workspace/PES1UG21CS924-1/main/hello2.cp -o output'
        }
    }

    stage('Test'){
        steps{
            sh './output'
        }
    }

    stage('Deploy'){
        steps{
            echo 'deploy'
        }
    }
  }
  post{
    failure{
        error 'Pipeline failed'
    }
  }
}


    


